// <auto-generated />
using System;
using BeerDrive.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeerDrive.Infrastructure.Migrations
{
    [DbContext(typeof(BeerDriveDbContext))]
    partial class BeerDriveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeerDrive.Domain.Entities.FileEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("FileEntries", (string)null);
                });

            modelBuilder.Entity("BeerDrive.Domain.Entities.FileEntry", b =>
                {
                    b.OwnsOne("BeerDrive.Domain.Entities.FileName", "Name", b1 =>
                        {
                            b1.Property<int>("FileEntryId")
                                .HasColumnType("int");

                            b1.Property<string>("Extension")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Extension");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Name");

                            b1.HasKey("FileEntryId");

                            b1.ToTable("FileEntries");

                            b1.WithOwner()
                                .HasForeignKey("FileEntryId");
                        });

                    b.OwnsOne("BeerDrive.Domain.Entities.FileSize", "Size", b1 =>
                        {
                            b1.Property<int>("FileEntryId")
                                .HasColumnType("int");

                            b1.Property<long>("SizeValue")
                                .HasColumnType("bigint")
                                .HasColumnName("SizeValue");

                            b1.Property<int>("Unit")
                                .HasColumnType("int")
                                .HasColumnName("Unit");

                            b1.HasKey("FileEntryId");

                            b1.ToTable("FileEntries");

                            b1.WithOwner()
                                .HasForeignKey("FileEntryId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Size")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
